branchProtection:
  - branch: '__DEFALT_BRANCH__'
    required_status_checks:
      strict: true
      contexts:
        - .github/dependabot.yml
        - build
    required_linear_history: true
    enforce_admins: false
    required_pull_request_reviews: null
    restrictions: null
