name: Docker Image CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: crazy-max/ghaction-docker-buildx@v1

      - name: Docker login
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
        run: docker login  -u $docker_username -p ${docker_password}

      - name: Run Buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          -t ${GITHUB_REPOSITORY}:sha-${GITHUB_SHA} --push .

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          -t ${GITHUB_REPOSITORY}:latest --push .
