name: Docker Image CI
on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: docker build -t ${GITHUB_REPOSITORY}:latest
      
    - name: Docker login
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: docker login  -u $docker_username -p ${docker_password}

    - name: Docker tag
      run: docker tag ${GITHUB_REPOSITORY}:latest ${GITHUB_REPOSITORY}:${GITHUB_SHA}

    - name: Docker push latest
      if: github.ref == 'master'
      run: docker push ${GITHUB_REPOSITORY}:latest

    - name: Docker push sha
      run: docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}
