name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag docker.pkg.github.com/chrisns/iot-zwave:${GITHUB_SHA}
        docker push docker.pkg.github.com/chrisns/iot-zwave:${GITHUB_SHA}
